site_name: Portfolio VoidSponge
theme:
  name: material
  palette: 
    scheme: slate 
    primary: indigo
nav:
  - Accueil: index.md
  - Cybersecurit√©:
    - 'SOC ELK': cybersecurite/soc-elk.md
  - IA:
    - 'Agent IA Cyber': ia/agent-ia.md
